# FROM python:3.10-slim
# WORKDIR /app
# # COPY . /app

# RUN MYSQLCLIENT_CFLAGS="-I/usr/include/mysql" MYSQLCLIENT_LDFLAGS="-L/usr/lib/x86_64-linux-gnu -lmysqlclient"
# # RUN apt-get update && apt-get install -y \
# #     gcc \
# #     default-libmysqlclient-dev
# RUN pip install mysql-connector-python
# RUN apt-get update \
#     && apt-get upgrade -y \
#     && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
#     && rm -rf /var/lib/apt/lists/*

# COPY requirements.txt requirements.txt
# RUN pip install -r requirements.txt
# COPY . /app

# # COPY . .
# ENV FLASK_APP=app.py

# EXPOSE 5000

# CMD ["flask", "run", "--host=0.0.0.0"]

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN apt-get update \
    && apt-get install -y gcc default-libmysqlclient-dev pkg-config \
    && rm -rf /var/lib/apt/lists/*

RUN pip install mysql-connector-python \
    && pip install -r /app/requirements.txt

COPY . /app

ENV FLASK_APP=app.py
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0"]

